//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notgitter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public byte[] timestamp { get; set; }
        public string UserName { get; set; }
        public long RepoId { get; set; }
        public int Uid { get; set; }
    
        public virtual Repo Repo { get; set; }
        public virtual User User { get; set; }
    }
}
