//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notgitter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Repoes = new HashSet<Repo>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> GithubId { get; set; }
        public byte[] online { get; set; }
        public int UserMessage_User_Id { get; set; }
    
        public virtual Message Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repo> Repoes { get; set; }
    }
}
